export const SongList = [
  {
    songId: 1,
    songTitle: "Bank On It",
    artist: "Burna Boy",
    src: "./Songs/[Waploaded_1221]Burna_Boy_-_Bank_On_It.mp3",
    img: "./Images/burna.webp",
  },
  {
    songId: 2,
    songTitle: "Dear God",
    artist: "Dax",
    src: "./Songs/Dax_-__Dear_God__(Official_Music_Video)(128k).mp3",
    img: "./Images/dax.jpg",
  },
  {
    songId: 3,
    songTitle: "Monster You Made",
    artist: "Burna Boy feat Chris Martin",
    src: "./Songs/[Waploaded_1233]Burna_Boy_-_Monsters_You_Made_feat_Chris_Martin.mp3",
    img: "./Images/burna.webp",
  },
  {
    songId: 4,
    songTitle: "Essence",
    artist: "Wizkid feat Tems",
    src: "./Songs/[Waploaded_209]Wizkid_-_Essense_ft_Tems.mp3",
    img: "./Images/Wizkid.webp",
  },
  {
    songId: 5,
    songTitle: "High",
    artist: "Adekunle Gold feat Davido",
    src: "./Songs/Adekunle Gold - High (feat.  Davido).mp3",
    img: "./Images/Adekunle-Gold-e1501504813504.jpeg",
  },
  {
    songId: 6,
    songTitle: "Lie",
    artist: "Kizz Daniel",
    src: "./Songs/Kizz_Daniel_Lie_9jaflaver.com_.mp3",
    img: "./Images/Kizz-Daniel-598x420.jpeg",
  },
  {
    songId: 7,
    songTitle: "Pour Me Water",
    artist: "Kizz Daniel",
    src: "./Songs/Kizz_Daniel_Pour_Me_Water_9jaflaver.com_.mp3",
    img: "./Images/Kizz-Daniel-598x420.jpeg",
  },
  {
    songId: 8,
    songTitle: "King James",
    artist: "MI Abaga",
    src: "./Songs/MI-Abaga-King-James.mp3",
    img: "./Images/MI-Abaga-700x700-1.jpg",
  },
  {
    songId: 9,
    songTitle: "Paloma",
    artist: "Mr-P Feat Singah",
    src: "./Songs/Mr-P-Feat.-Singah-Paloma.mp3",
    img: "./Images/The Catalyst 2 (1).png",
  },
  {
    songId: 10,
    songTitle: "Gra Gra",
    artist: "Timaya",
    src: "./Songs/Timaya_-_Gra_Gra_(Official_Video).mp3",
    img: "./Images/timayatimaya-20190411-0002.jpg",
  },
  {
    songId: 11,
    songTitle: "Cold Outside",
    artist: "Timaya",
    src: "./Songs/Timaya_ft_Buju_-_Cold_Outside.mp3",
    img: "./Images/timayatimaya-20190411-0002.jpg",
  },
];
